### ISSUE TITLE
JavaScript Troubleshooting Tutorial: ReferenceError: "x" is not defined

### ISSUE THREAD

**Issue by ltagliaferri** [sourcegraph/learn#239]
Write a short tutorial on JavaScript's `ReferenceError: "x" is not defined` error message, following the "[How to troubleshoot Python ZeroDivisionError](https://learn.sourcegraph.com/how-to-troubleshoot-python-zerodivisionerror)" example tutorial.

The tutorial should be organized as follows:

```
---
title: How to troubleshoot JavaScript ReferenceError "x" is not defined
author: your name
tags: [tutorial, JavaScript, troubleshooting]
publicationDate: today's date
description: Learn how to error handle JavaScript ReferenceError, "x" is not defined
image: https://storage.googleapis.com/sourcegraph-assets/learn/headers/sourcegraph-learn-header.png
imageAlt: Sourcegraph Learn
browserTitle: ReferenceError, "x" is not defined in JavaScript error handling
type: posts
---

Introduction with the error message

## Reproducing the error

Show how the error can be created.

## Solution 1

Provide a possible solution.

## Solution 2

Provide another solution.

## (optional) Solution 3

Optionally provide a third solution. 

## Learn more

Search across open source JavaScript repositories that have the `ReferenceError` to understand the message more.

<SourcegraphSearch query="ReferenceError: "x" is not defined" patternType="literal"/>

Check out more Sourcegraph Learn tutorials on [JavaScript](https://learn.sourcegraph.com/tags/javascript).
```

If this seems like a tutorial that you can write effectively for the developer community, please follow our [Hacktoberfest 2021 contributor guidelines](https://github.com/sourcegraph/learn/blob/main/docs/hacktoberfest-2021.md) to proceed.

**Comment by Afoma** [comment]
Hi, I would like to work on this.

**Comment by Afoma** [comment]
Yes, I'm submitting it today. I'm sorry for the delay.

**Comment by Afoma** [comment]
Okay, I'm submitting today.

I'm sorry for the delay.

**Comment by Afoma** [comment]
Hello Itaglia, I pushed my code some weeks ago. Could you please merge it?

**Comment by Afoma** [comment]
Hello, @ltagliaferri  I pushed my code some weeks ago. Could you please merge it?

**Comment by ltagliaferri** [comment]
Hi @Afoma, there is no pull request for this issue
