### ISSUE TITLE
Linux Troubleshooting Tutorial: No such file or directory

### ISSUE THREAD

**Issue by ltagliaferri** [sourcegraph/learn#257]
Write a short tutorial on Linux's `No such file or directory` error message, following the "[How to troubleshoot Python ZeroDivisionError](https://learn.sourcegraph.com/how-to-troubleshoot-python-zerodivisionerror)" example tutorial.

The tutorial should be organized as follows:

```
---
title: How to troubleshoot Linux error No such file or directory
author: your name
tags: [tutorial, Linux, troubleshooting]
publicationDate: today's date
description: Learn how to error handle No such file or directory in Linux
image: https://storage.googleapis.com/sourcegraph-assets/learn/headers/sourcegraph-learn-header.png
imageAlt: Sourcegraph Learn
browserTitle: No such file or directory in Linux error handling
type: posts
---

Introduction with the error message

## Reproducing the error

Show how the error can be created.

## Solution 1

Provide a possible solution.

## Solution 2

Provide another solution.

## (optional) Solution 3

Optionally provide a third solution. 

## Learn more

Search across open source JavaScript repositories that have the `No such file or directory` to understand the message more.

<SourcegraphSearch query="No such file or directory" patternType="literal"/>

Check out more Sourcegraph Learn tutorials on [Linux](https://learn.sourcegraph.com/tags/linux).
```

If this seems like a tutorial that you can write effectively for the developer community, please follow our [Hacktoberfest 2021 contributor guidelines](https://github.com/sourcegraph/learn/blob/main/docs/hacktoberfest-2021.md) to proceed.

**Comment by jayendranarumugam** [comment]
I'll  give it a try for this issue. Can you assign this to me @ltagliaferri ?

**Comment by ltagliaferri** [comment]
Hi @davidylee, this issue already has a pull request associated with it. Is there another Linux error you would like to write a tutorial on? Feel free to open an issue or let me know what the error is and I can set one up for you 😄

**Comment by davidylee** [comment]
> Hi @davidylee, this issue already has a pull request associated with it. Is there another Linux error you would like to write a tutorial on? Feel free to open an issue or let me know what the error is and I can set one up for you 😄

Hi @ltagliaferri thanks, perhaps I can do one for another common Linux error 'Permission denied' ?

**Comment by ltagliaferri** [comment]
@davidylee:
https://github.com/sourcegraph/learn/issues/284

@umegbewe:
https://github.com/sourcegraph/learn/issues/285
