### ISSUE TITLE
`-lang` example and possibly others don't work correctly

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/learn#262]
Clicking on search for this example for `-lang:java`:

![Screen Shot 2021-10-05 at 5 54 35 PM](https://user-images.githubusercontent.com/888624/136123939-928cdbdc-4446-4755-b73f-13dcd7f33a8c.png)

Takes you to [this search on Sourcegraph](https://sourcegraph.com/search?q=%E2%80%8B%E2%80%8B-lang%3Ajava&_ga=2.233108958.1758666441.1633370438-456845826.1624503716&_gac=1.120601338.1631045125.Cj0KCQjwm9yJBhDTARIsABKIcGYg2fjyP-Jolqo7KAQYNqTRctH0v4nChooWmqwFxJX5LDcVcrXALCwaAmAIEALw_wcB)

Which doesn't show you files that aren't Java, but instead matches that exact string. Weird, how come?

![Screen Shot 2021-10-05 at 5 56 10 PM](https://user-images.githubusercontent.com/888624/136124014-a200d8c5-61c2-4cb1-9038-4f5b7d0b9b2f.png)

It turns out something is inserting zero-width spaces, possibly because of the `-`, and prepending it. You can see that this was added in the URL in the screenshot above: the query parameter starts with `%E2%80%8B%E2%80%8B` and then `-lang:java`. If we inspect the HTML on the learn website, we see that's the case:

![Screen Shot 2021-10-05 at 5 57 56 PM](https://user-images.githubusercontent.com/888624/136124142-57483af1-ee5a-48ff-8f07-1e76cece3947.png)

Not sure what the fix is, but something is injecting that into the HTML which causes the URL to link to a query that Sourcegraph interprets containing that zero-width space character and so `-lang` doesn't work.

@ltagliaferri for visibility

**Comment by ltagliaferri** [comment]
Thanks @rvantonder, this is a good catch. @katjuell this is the [Language-specific search section of the cheat sheet](https://learn.sourcegraph.com/how-to-search-code-with-sourcegraph-a-cheat-sheet#language-specific-search).
