### ISSUE TITLE
Linux Troubleshooting Tutorial: Permission denied

### ISSUE THREAD

**Issue by ltagliaferri** [sourcegraph/learn#284]
Write a short tutorial on Linux's `Permission denied` error message, following the "[How to troubleshoot Python ZeroDivisionError](https://learn.sourcegraph.com/how-to-troubleshoot-python-zerodivisionerror)" example tutorial.

The tutorial should be organized as follows:

```
---
title: How to troubleshoot the Linux error Permission denied
author: your name
tags: [tutorial, Linux, troubleshooting]
publicationDate: today's date
description: Learn how to error handle Permission denied in Linux
image: https://storage.googleapis.com/sourcegraph-assets/learn/headers/sourcegraph-learn-header.png
imageAlt: Sourcegraph Learn
browserTitle: Permission denied in Linux error handling
type: posts
---

Introduction with the error message

## Reproducing the error

Show how the error can be created.

## Solution 1

Provide a possible solution.

## Solution 2

Provide another solution.

## (optional) Solution 3

Optionally provide a third solution. 

## Learn more

Search across open source repositories that have the `Permission denied` to understand the message more.

<SourcegraphSearch query="Permission denied" patternType="literal"/>

Check out more Sourcegraph Learn tutorials on [Linux](https://learn.sourcegraph.com/tags/linux).
```

If this seems like a tutorial that you can write effectively for the developer community, please follow our [Hacktoberfest 2021 contributor guidelines](https://github.com/sourcegraph/learn/blob/main/docs/hacktoberfest-2021.md) to proceed.

**Comment by ltagliaferri** [comment]
@davidylee — here is the issue for you

**Comment by agitated-newton** [comment]
Hey @ltagliaferri, given that there hasn't been any activity on this for the past few days - can I pick this up? I should be done with this in a couple of hours!

**Comment by ltagliaferri** [comment]
@agitated-newton I will assign to you in the meantime
